---
layout: legal
title: "Terms of Service"
date: November 3, 2015
author: Erik LaBianca <erik@7thsense.io>
---
= TERMS OF SERVICE

Please read this Terms of Service agreement before using the services offered
by Telepath Data Inc. dba Seventh Sense, (“Seventh Sense”, “us” or “we”).

THIS AGREEMENT GOVERNS YOUR ACQUISITION AND USE OF OUR SERVICES.

IF YOU REGISTER FOR A FREE TRIAL FOR OUR SERVICES, THIS AGREEMENT WILL ALSO
GOVERN THAT FREE TRIAL.

BY ACCEPTING THIS AGREEMENT, EITHER BY CLICKING A BOX INDICATING YOUR
ACCEPTANCE OR BY EXECUTING AN ORDER FORM THAT REFERENCES THIS AGREEMENT, YOU
AGREE TO THE TERMS OF THIS AGREEMENT. IF YOU ARE ENTERING INTO THIS AGREEMENT
ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE
AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS AND CONDITIONS,
IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS
AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT AGREE WITH
THESE TERMS AND CONDITIONS, YOU MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE
THE SERVICES.

== 1. Definitions

"Agreement" means these Terms of Service and all materials referred or linked
to in here.

"Billing Period" means the period for which you agree to prepay fees under an
Order Form, which will be the same as or shorter than the Subscription Term.
For example, if you subscribe to the Subscription Service for a one (1) year
Initial Subscription Term, with a twelve (12) month upfront payment, the
Billing Period will be twelve (12) months.

"Contact" means a single customer, prospect, lead, or other individual (other
than a User) whose Contact Information is stored by you in the Subscription
Service.

"Customer Data" means all information that you submit or collect via the
Subscription Service.

“Documentation” means Our online user guides, documentation, and help and
training materials, as updated from time to time, accessible via
help.theseventhsense.com or login to the Subscription Service.

"Maximum Contacts" means the maximum number of Contacts you are permitted to
use with the Subscription Service as identified in your Order Form.

"Order Form" or "Order" means the form or online subscription process by which
you agree to subscribe to the Subscription Service and purchase Consulting
Services. Most Orders are completed through our online payment process.

"Sensitive Information" means credit or debit card numbers; personal financial
account information; Social Security numbers; passport numbers; driver’s
license numbers or similar identifiers; racial or ethnic origin; physical or
mental health condition or information; or other employment, financial or
health information, including any information subject to regulations, laws or
industry standards designed to protect data privacy and security, such as the
Health Insurance Portability and Accountability Act and the Payment Card
Industry Data Security Standards.

"Subscription Fee" means the amount you pay for the Subscription Service.

"Subscription Service" means our web-based applications, tools and platform
that you have subscribed to by an Order Form or that we otherwise make
available to you, and developed, operated, and maintained by us, accessible via
https://theseventhsense.com or another designated URL, and any ancillary
products and services that we provide to you.

"Subscription Term" means the Initial Subscription Term and all Renewal
Subscription Terms. + "Third-Party Products" means non-embedded products and
professional services that are provided by third parties which interoperate
with or are used in connection with the Subscription Service.

"Users" means your employees, representatives, consultants, contractors or
agents who are authorized to use the Subscription Service for your benefit and
have unique user identifications and passwords for the Subscription Service.

== 2. Free Trial

If You register on our website for a free trial, We will make
one or more Services available to You on a trial basis free of charge until the
earlier of (a) the end of the free trial period for which you registered to use
the applicable Service(s), or (b) the start date of any Purchased Service
subscriptions ordered by You for such Service(s). Additional trial terms and
conditions may appear on the trial registration web page. Any such additional
terms and conditions are incorporated into this Agreement by reference and are
legally binding.

ANY DATA YOU ENTER INTO THE SERVICES, AND ANY CUSTOMIZATIONS MADE TO THE
SERVICES BY OR FOR YOU, DURING YOUR FREE TRIAL WILL BE PERMANENTLY LOST UNLESS
YOU PURCHASE A SUBSCRIPTION TO THE SAME SERVICES AS THOSE COVERED BY THE TRIAL,
PURCHASE UPGRADED SERVICES, OR EXPORT SUCH DATA, BEFORE THE END OF THE TRIAL
PERIOD. YOU CANNOT TRANSFER DATA ENTERED OR CUSTOMIZATIONS MADE DURING THE FREE
TRIAL TO A SERVICE THAT WOULD BE A DOWNGRADE FROM THAT COVERED BY THE TRIAL
(E.G., FROM MARKETING EDITION TO INDIVIDUAL EDITION); THEREFORE, IF YOU
PURCHASE A SERVICE THAT WOULD BE A DOWNGRADE FROM THAT COVERED BY THE TRIAL,
YOU MUST EXPORT YOUR DATA BEFORE THE END OF THE TRIAL PERIOD OR YOUR DATA WILL
BE PERMANENTLY LOST.

NOTWITHSTANDING SECTION  (REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND
DISCLAIMERS), DURING THE FREE TRIAL THE SERVICES ARE PROVIDED “AS-IS” WITHOUT
ANY WARRANTY.

== 3. Use of the Subscription Services

3.1. *Our Responsibilities*. During the Subscription Term, we will provide you
access to use the Subscription Service
as described in this Agreement.

a. We try to make the Subscription Service available 24 hours a day, 7 days a
week, except for planned down-time for maintenance.

b. *Support*. Support is included in your Subscription Fee. Phone support for
the Subscription Service is available 9AM to 5PM Eastern Time (GMT-5), Monday
through Friday, excluding US national holidays. We accept webform support
questions 24 Hours per Day x 7 Days per Week at
https://theseventhsense.zendesk.com. Webform responses are provided during
phone support hours only. We attempt to respond to webform support questions
within one business day; in practice, our responses are generally even faster.
We do not promise or guarantee any specific response time.

c. *Our Protection of Your Data*. We will maintain administrative, physical,
and technical safeguards for protection of the security, confidentiality and
integrity of Your Data. Those safeguards will include, but will not be limited
to, measures for preventing access, use, modification or disclosure of Your
Data by Our personnel except (a) to provide the Purchased Services and prevent
or address service or technical problems, (b) as compelled by law in accordance
with Section 8.3 (Compelled Disclosure) below, or (c) as You expressly permit
in writing.

d. *Our Personnel*. We will be responsible for the performance of Our personnel
(including Our employees and contractors) and their compliance with Our
obligations under this Agreement, except as otherwise specified herein.

3.2. *Your Responsibilities* To realize the full value of the Subscription
Service, your participation and effort are needed. Resources that may be
required from you include a Project Manager, one or more Content Creators, a
Sales Sponsor, an Executive Sponsor and a Technical Resource. Responsibilities
that may be required include identifying success criteria, developing a
training schedule and supporting the integration of the Subscription Service
with data sources and other sales and marketing systems.

a. *Your Protection of the Subscription Service*. You shall: (i) be responsible
for Users’ compliance with this Agreement; (ii) be responsible for the
accuracy, quality and legality of Your Data and of the means by which You
acquire Your Data; (iii) use commercially reasonable efforts to prevent
unauthorized access to or use of the Subscription Services, and notify Us
promptly of any such unauthorized access or use; and (iv) use the Subscription
Services only in accordance with the User Documentation and applicable laws and
government regulations.

b. *No Sensitive Information* YOU AGREE NOT TO USE THE SUBSCRIPTION SERVICE
TO COLLECT, MANAGE OR PROCESS SENSITIVE INFORMATION. WE WILL NOT HAVE ANY
LIABILITY THAT MAY RESULT FROM YOUR USE OF THE SUBSCRIPTION SERVICE TO COLLECT
OR MANAGE SENSITIVE INFORMATION.

3.3. *Limits*. Limits may apply to the number of Contacts, Jobs, Data Points,
or other types of Customer Data you may store in the Subscription Service. Any
limits will be specified in your Order Form and this Agreement.

3.4. *Modifications*. We modify the Subscription Service from time to time,
including by adding or deleting features and functions, in an effort to improve
your experience. But we will not make changes to the Subscription Service that
materially reduce the functionality of the Subscription Service provided to you
during the Subscription Term. We might provide some or all elements of the
Subscription Service through third party service providers.

3.5. *Beta Services*. From time to time, We may invite You to try Beta Services
at no charge. You may accept or decline any such trial in Your sole discretion.
Beta Services will be clearly designated as beta, pilot, limited release,
developer preview, non-production, evaluation or by a description of similar
import. Beta Services are for evaluation purposes and not for production use,
are not considered “Services” under this Agreement, are not supported, and may
be subject to additional terms. Unless otherwise stated, any Beta Services
trial period will expire upon the earlier of one year from the trial start date
or the date that a version of the Beta Services becomes generally available. We
may discontinue Beta Services at any time in Our sole discretion and may never
make them generally available. We will have no liability for any harm or damage
arising out of or in connection with a Beta Service.

== 4. Fees and Payments for Purchased Services

a. *Subscription Fees*. The Subscription Fee will remain fixed during the
Subscription Term unless you
    (i) exceed your Maximum Contacts;
    (ii) change products or base packages, or
    (iii) subscribe to additional features or products, including additional Contacts.
Where a price change applies to you, we will charge or invoice you under the
new price structure, starting with the next Billing Period in the Subscription
Term, except as provided below under 'Fee Adjustments During a Billing Period'.
In order to avoid additional charges, you should purchase the appropriate tier
of Subscription Service for your anticipated needs. We will monitor or audit
remotely the number of Contacts in the Subscription Service. This information
is also available to you on the dashboard of the Seventh Sense application.

b. *Fee Adjustments in Next Billing Period*. If you exceed your Maximum
Contacts in a Billing Period, then your Subscription Fee will be adjusted at
the beginning of the next Billing Period up to the current base package and
tier price which corresponds with the maximum number of Contacts from the prior
Billing Period. This process will continue for each Billing Period during the
Subscription Term. Our pricing and limits will be as set forth at
https://theseventhsense.com/pricing. We determine the number of Contacts in the
Subscription Service and the number of emails you sent. At your request, we
will provide you with the detail we used to reach our conclusion. Once
increased, your Subscription Fee will not decrease, even if there is a
subsequent reduction in the number of Contacts or emails sent.

c. *Fee Adjustments During a Billing Period*. The Subscription Fee will
increase during a Billing Period if you change products or subscribe to
additional features for use during the Billing Period.

d. *Payment by credit card*. If you are paying by credit card, you authorize us
to charge your credit card or bank account for all fees payable during the
Subscription Term. You further authorize us to use a third party to process
payments, and consent to the disclosure of your payment information to such
third party.

e. *Payment against invoice*. If you are paying by invoice, we will invoice you
at the beginning of the Initial Subscription Term and at the beginning of each
subsequent Billing Period, and other time during the Subscription Term when
fees are payable. All amounts invoiced are due and payable within thirty (30)
days from the date of the invoice, unless otherwise specified in the Order
Form.

f. *Payment Information*. You will keep your contact information, billing
information and credit card information (where applicable) up to date. Changes
may be made on your Subscriptions page within the Subscription Service. All
payment obligations are non-cancelable and all amounts paid are non-refundable,
except as specifically provided for in this Agreement. All fees are due and
payable in advance throughout the Subscription Term.

g. *Sales Tax*. All fees are exclusive of taxes, which we will charge as
applicable. You agree to pay any taxes applicable to your use of the
Subscription Service. You shall have no liability for any taxes based upon our
gross revenues or net income.

h. *Future Functionality*. You agree that Your purchases are not contingent on
the delivery of any future functionality or features, or dependent on any oral
or written public comments made by Us regarding future functionality or
features.

== 5. Proprietary Rights and Licenses

a. *Reservation of Rights*. This is an
Agreement for access to and use of the Subscription Service, and you are not
granted a license to any software by this Agreement. The Subscription Service
is protected by intellectual property laws. The Subscription Service belong to
and are the property of us or our licensors (if any). We retain all ownership
rights in the Subscription Service. You agree not to copy, rent, lease, sell,
distribute, or create derivative works based on the Subscription Service in
whole or in part, by any means, except as expressly authorized in writing by
us. Telepath Data, Seventh Sense, “Knowing When”, the Brain design, the Seventh
Sense logo and other marks that we use from time to time are our trademarks.
You may not use any of these without our prior written permission.

b. *Your Data*. As between You and Us, You shall own all Your Data, including
all reports, statistics, and other data to the extent generated solely from
Your Data, and all intellectual property rights therein; provided, however,
that during the term of this Agreement, You grant to Us a worldwide,
non-exclusive, royalty-free license to aggregate or compile Your Data with
other data, including the customer data of other Seventh Sense customers so
long as such aggregation or compilation omits any data that would enable the
identification of You, Your clients, or any individual, company or organization
(“Aggregated Data”). We shall have a worldwide, perpetual, royalty-free license
to use, modify, distribute and create derivative works based on such Aggregated
Data, including all reports, statistics or analyses created or derived
therefrom. Additionally, You grant to Us the right to access Your Data to
provide feedback to You concerning Your use of the Marketing Cloud Services.

c. *License by You to Use Feedback*. You grant to Us and Our Affiliates a
worldwide, perpetual, irrevocable, royalty-free license to use and incorporate
into the Services any suggestion, enhancement request, recommendation,
correction or other feedback provided by You or Users relating to the operation
of the Services.

d. *Publicity*. You grant us the right to add your name and company logo to our
customer list and website.

e. *Federal Government End Use Provisions*. We provide the Services, including
related software and technology, for ultimate federal government end use solely
in accordance with the following: Government technical data and software rights
related to the Services include only those rights customarily provided to the
public as defined in this Agreement. This customary commercial license is
provided in accordance with FAR 12.211 (Technical Data) and FAR 12.212
(Software) and, for Department of Defense transactions, DFAR 252.227-7015
(Technical Data – Commercial Items) and DFAR 227.7202-3 (Rights in Commercial
Computer Software or Computer Software Documentation). If a government agency
has a need for rights not granted under these terms, it must negotiate with Us
to determine if there are acceptable terms for granting those rights, and a
mutually acceptable written addendum specifically granting those rights must be
included in any applicable agreement.

== 6. Confidentiality

a. *Definition*. “Confidential Information” means all information disclosed by a party
(“Disclosing Party”) to the other party (“Receiving Party”), whether orally or
in writing, that is designated as confidential or that reasonably should be
understood to be confidential given the nature of the information and the
circumstances of disclosure. Your Confidential Information includes Your Data;
Our Confidential Information includes the Services and Content; and
Confidential Information of each party includes the terms and conditions of
this Agreement and all Order Forms (including pricing), as well as business and
marketing plans, technology and technical information, product plans and
designs, and business processes disclosed by such party. However, Confidential
Information does not include any information that (i) is or becomes generally
known to the public without breach of any obligation owed to the Disclosing
Party, (ii) was known to the Receiving Party prior to its disclosure by the
Disclosing Party without breach of any obligation owed to the Disclosing Party,
(iii) is received from a third party without breach of any obligation owed to
the Disclosing Party, or (iv) was independently developed by the Receiving
Party.

b. *Protection*. The Receiving Party will use the
same degree of care that it uses to protect the confidentiality of its own
confidential information of like kind (but not less than reasonable care) (i)
not to use any Confidential Information of the Disclosing Party for any purpose
outside the scope of this Agreement, and (ii) except as otherwise authorized by
the Disclosing Party in writing, to limit access to Confidential Information of
the Disclosing Party to those of its and its Affiliates’ employees and
contractors who need that access for purposes consistent with this Agreement
and who have signed confidentiality agreements with the Receiving Party
containing protections no less stringent than those herein.

c. *Compelled Disclosure*. The Receiving Party may disclose Confidential
Information of the Disclosing Party to the extent compelled by law to do so,
provided the Receiving Party gives the Disclosing Party prior notice of the
compelled disclosure (to the extent legally permitted) and reasonable
assistance, at the Disclosing Party's cost, if the Disclosing Party wishes to
contest the disclosure. If the Receiving Party is compelled by law to disclose
the Disclosing Party’s Confidential Information as part of a civil proceeding
to which the Disclosing Party is a party, and the Disclosing Party is not
contesting the disclosure, the Disclosing Party will reimburse the Receiving
Party for its reasonable cost of compiling and providing secure access to that
Confidential Information.

== 7. Third-Party Sites and Products

Third-Party Sites and Products are not
under our control. Third-Party Sites and Products are provided to you only as a
convenience, and the availability of any Third-Party Site or Product does not
mean we endorse, support or warranty the Third-Party Site or Product.

The Service may include links to other websites, services or resources on the
Internet that are owned and operated by online merchants and other third
parties. You acknowledge that we are not responsible for the availability,
content, legality, appropriateness or any other aspect of any third-party site.
Your use of third-party sites is at your own risk and subject to the terms of
use and privacy policies of each site, for which we are not responsible and
which we encourage you to review.

Certain Services are organized by third parties. Additionally, certain other
Services, including registration, scheduling and mobile applications, are
provided by or dependent on third parties. Seventh Sense offers no guarantees
and assumes no responsibility or liability of any type with respect to content,
products and services provided by any third party.

Integration with Non Seventh Sense Applications. The Subscription Services may
contain features designed to interoperate with Non Seventh Sense Applications.
To use such features, You may be required to obtain access to such Non Seventh
Sense Applications from their providers. If the provider of any such Non
Seventh Sense Application ceases to make the Non Seventh Sense Application
available for interoperation with the corresponding Subscription Service
features on reasonable terms, We may cease providing such Subscription Service
features without entitling You to any refund, credit, or other compensation.


== 8. Disclaimers; Limitations of Liability

a. *Representations*. Each party represents that it has validly entered into
this Agreement and has the legal power to do so.

b. *Disclaimer of Warranties.* THE SERVICE IS PROVIDED BY SEVENTH SENSE ON AN
“AS IS” AND ON AN “AS AVAILABLE” BASIS. TO THE FULLEST EXTENT PERMITTED BY
APPLICABLE LAW, SEVENTH SENSE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY
KIND, EXPRESS OR IMPLIED, REGARDING  THE SUITABILITY, RELIABILITY,
AVAILABILITY, TIMELINESS, SECURITY OR ACCURACY OF THE SUBSCRIPTION SERVICE,
DATA MADE AVAILABLE FROM THE SUBSCRIPTION SERVICE. COMPANY WILL HAVE NO
LIABILITY FOR ANY INTERRUPTIONS IN THE USE OF THE SERVICE. SEVENTH SENSE
DISCLAIMS ALL WARRANTIES WITH REGARD TO THE INFORMATION PROVIDED, INCLUDING THE
IMPLIED WARRANTIES OF MERCHANTABILITY, PERFORMANCE AND FITNESS FOR A PARTICULAR
PURPOSE, AND WARRANTIES OF NON-INFRINGEMENT.

c. *No Indirect Damages*. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
EITHER PARTY BE LIABLE FOR ANY INDIRECT, PUNITIVE, OR CONSEQUENTIAL DAMAGES,
INCLUDING LOST PROFITS OR BUSINESS OPPORTUNITIES. +

d. *Limitation of Liability*. EXCEPT FOR YOUR LIABILITY FOR PAYMENT OF FEES,
YOUR LIABILITY ARISING FROM YOUR INDEMNITY OBLIGATIONS, AND YOUR LIABILITY FOR
VIOLATION OF OUR INTELLECTUAL PROPERTY RIGHTS, IF, NOTWITHSTANDING THE OTHER
TERMS OF THIS AGREEMENT, EITHER PARTY IS DETERMINED TO HAVE ANY LIABILITY TO
THE OTHER PARTY OR ANY THIRD PARTY, THE PARTIES AGREE THAT THE AGGREGATE
LIABILITY OF A PARTY WILL BE LIMITED TO THE TOTAL AMOUNTS YOU HAVE ACTUALLY
PAID FOR THE SUBSCRIPTION SERVICE IN THE TWELVE MONTH PERIOD PRECEDING THE
EVENT GIVING RISE TO A CLAIM.

d. *Third Party Products*. WE DISCLAIM ALL LIABILITY WITH RESPECT TO
THIRD-PARTY PRODUCTS THAT YOU USE. OUR LICENSORS SHALL HAVE NO LIABILITY OF ANY
KIND UNDER THIS AGREEMENT.

YOU UNDERSTAND AND AGREE THAT ABSENT YOUR AGREEMENT TO THIS LIMITATION OF
LIABILITY, WE WOULD NOT PROVIDE THE SUBSCRIPTION SERVICE TO YOU.

== Indemnification

You will indemnify, defend and hold us harmless, at your
expense, against any third-party claim, suit, action, or proceeding (each, an
"Action") brought against us (and our officers, directors, employees, agents,
service providers, licensors, and affiliates) by a third party not affiliated
with us to the extent that such Action is based upon or arises out of (a)
unauthorized or illegal use of the Subscription Service by you; (b) your
noncompliance with or breach of this Agreement, (c) your use of Third-Party
Products, or (d) the unauthorized use of the Subscription Service by any other
person using your User information. We will: notify you in writing within
thirty (30) days of our becoming aware of any such claim; give you sole control
of the defense or settlement of such a claim; and provide you (at your expense)
with any and all information and assistance reasonably requested by you to
handle the defense or settlement of the claim. You shall not accept any
settlement that (i) imposes an obligation on us; (ii) requires us to make an
admission; or (iii) imposes liability not covered by these indemnifications or
places restrictions on us without our prior written consent.

== Term and Termination

a. *Initial Subscription Term*. The initial
subscription term shall begin on the effective date of your subscription and
expire at the end of the period selected during the subscription process
("Initial Subscription Term").

b. *Renewal Subscription Term*. Unless one of us gives the other written notice
that it does not intend to renew the subscription, this Agreement will
automatically renew for the shorter of the Initial Subscription Term or one
year ("Renewal Subscription Term"). Written notice of non-renewal must be sent
no more than ninety (90) days but no less than forty-five (45) days in advance
of the end of the Subscription Term. The Renewal Subscription Term will be on
the current terms and conditions of this Agreement, and subject to the renewal
pricing provided for in your Order Form or, if not specified in the Order Form,
on our standard pricing available at *http://www.theseventhsense.com/pricing/*.
In addition, on renewal, the current product usage limits at
*http://www.theseventhsense.com/pricing/* will apply to your subscription,
unless otherwise agreed to by you and Seventh Sense. Should you decide not to
renew, you may send the notice of non-renewal by email to
*support@theseventhsense.com*.

c. *End of Subscription Term*. The Subscription Term will end on the expiration
date and cannot be canceled before its expiration.

d. *Termination for Cause*. Either party may terminate this Agreement for
cause: (i) upon thirty (30) days’ notice to the other party of a material
breach if such breach remains uncured at the expiration of such period, or (ii)
immediately, if the other party becomes the subject of a petition in bankruptcy
or any other proceeding relating to insolvency, liquidation or assignment for
the benefit of creditors. This Agreement may not otherwise be terminated prior
to the end of the Subscription Term.

e. *Suspension for Prohibited Acts*. We may suspend any User’s access to the
Subscription Service for: (i) use of the Subscription Service in a way that
violates applicable local, state, federal, or foreign laws or regulations or
the terms of this Agreement.

f. *Suspension for Non-Payment*. We may suspend your access to all or any part
of the Subscription Service upon ten (10) days’ notice to you of non-payment of
any amount past due. We will not suspend the Subscription Service while you are
disputing the applicable charges reasonably and in good faith and are
cooperating diligently to resolve the dispute. If the Subscription Service is
suspended for non-payment, we may charge a re-activation fee to reinstate the
Subscription Service.

g. *Effect of Termination or Expiration*. Upon termination or expiration of
this Agreement, you will stop all use of the Subscription Service. If you
terminate this Agreement for cause, we will promptly refund any prepaid but
unused fees covering use of the Subscription Service after termination. If we
terminate this Agreement for cause, you will promptly pay all unpaid fees due
through the end of the Subscription Term. Fees are otherwise non-refundable.

h. *Retrieval of Customer Data*. As long as you have paid all fees owed to us,
if you make a written request within thirty (30) days after termination or
expiration of your Subscription, we will provide you with temporary access to
the Subscription Service to retrieve, or we will provide you with copies of,
all Customer Data then in our possession or control. We may withhold access to
Customer Data until you pay any fees owed to us. Thirty (30) days after
termination or expiration of your Subscription, we will have no obligation to
maintain or provide you the Customer Data and may, unless legally prohibited,
delete all Customer Data in our systems or otherwise in our control.

== General

a. *Amendment; No Waiver*. We may update and change any part or all
of these Terms of Service, including the fees and charges associated with the
use of the Subscription Service. If we update or change these Terms of Service,
the updated Terms of Service will be posted at
https://theseventhsense.com/legal/terms-of-service/. The updated Terms of
Service will become effective and binding on the next business day after it is
posted. When we change these Terms of Service, the "Last Modified" date above
will be updated to reflect the date of the most recent version. We encourage
you to review these Terms of Service periodically.
+
If you do not agree with a modification to the Terms of Service, you must
notify us in writing within thirty (30) days after receiving notice of
modification. If you give us this notice, your subscription will continue to be
governed by the terms and conditions of the Terms of Service prior to
modification for the remainder of your current term. Upon renewal, the Terms of
Service published by us on our website will apply.
+
No delay in exercising any right or remedy or failure to object will be a
waiver of such right or remedy or any other right or remedy. A waiver on one
occasion will not be a waiver of any right or remedy on any future occasion.

b. *Governing Jurisdiction*. These Terms will be governed by the laws of the
Commonwealth of Virginia, excluding its choice of law rules, and the United
States of America, without reference to any conflict of laws provisions. Any
dispute arising from or relating to the subject matter of these Terms will be
finally settled by arbitration in Arlington in the Commonwealth of Virginia,
using the English language in accordance with the Arbitration Rules and
Procedures of JAMS then in effect. Judgment may be entered on the arbitral
award in any court having jurisdiction. The arbitral award will be final and
binding. Each party retains the right to seek judicial assistance: (i) to
compel arbitration; (ii) to obtain interim measures of protection prior to or
pending arbitration; (iii) to seek injunctive relief in the courts of any
jurisdiction as may be necessary and appropriate to protect the unauthorized
disclosure of its proprietary or confidential information; and (iv) to enforce
any decision of the arbitrator, including the final award.

c. *Force Majeure*. Neither party will be responsible for failure or delay of
performance if caused by: an act of war, hostility, or sabotage; act of God;
electrical, internet, or telecommunication outage that is not caused by the
obligated party; government restrictions; or other event outside the reasonable
control of the obligated party. Each party will use reasonable efforts to
mitigate the effect of a force majeure event.

d. *Actions Permitted*. Except for actions for nonpayment or breach of a
party’s proprietary rights, no action, regardless of form, arising out of or
relating to this Agreement may be brought by either party more than one (1)
year after the cause of action has accrued.

e. *Relationship of the Parties*. The parties are independent contractors. This
Agreement does not create a partnership, franchise, joint venture, agency,
fiduciary, or employment relationship between the parties.

f. *Compliance with Laws*. We will comply with all U.S. state and federal laws
in our provision of the Subscription Service and our processing of Customer
Data. We reserve the right at all times to disclose any information as
necessary to satisfy any law, regulation, legal process or governmental
request. You will comply with all laws in your use of the Subscription Service,
including any applicable export laws.

g. *Severability*. If any part of this Agreement or an Order Form is determined
to be invalid or unenforceable by applicable law, then the invalid or
unenforceable provision will be deemed superseded by a valid, enforceable
provision that most closely matches the intent of the original provision and
the remainder of this Agreement will continue in effect.

h. *Attorney Fees*. You shall pay on demand all of Our reasonable attorney fees
and other costs incurred by Us to collect any fees or charges due Us under this
Agreement following Your breach of Section 7.2 (Invoicing and Payment).

i. *Notices*. Notice will be sent to the contact address set forth herein, and
will be deemed delivered as of the date of actual receipt.
+
To Seventh Sense: Telepath Data Inc, 2017 N Dinwidde ST, Arlington VA 22007
+
To you: your address as provided in our Seventh Sense account information for
you. We may give electronic notices by general notice via the Subscription
Service and may give electronic notices specific to you by email to your e-mail
address(es) on record in our account information for you or through the
notifications center of the Subscription Service. We may give notice to you by
telephone calls to the telephone numbers on record in our account information
for you. You must keep all of your account information current.

j. *Entire Agreement*. This Agreement (including each Order Form and Statement
of Work), along with our Privacy Policy, is the entire agreement between us for
the Subscription Service and supersedes all other proposals and agreements,
whether electronic, oral or written, between us. We object to and reject any
additional or different terms proposed by you, including those contained in
your purchase order, acceptance or website. Our obligations are not contingent
on the delivery of any future functionality or features of the Subscription
Service or dependent on any oral or written public comments made by us
regarding future functionality or features of the Subscription Service. We
might make versions of this Agreement available in languages other than
English.  If we do, the English version of this Agreement will govern our
relationship and the translated version is provided for convenience only and
will not be interpreted to modify the English version of this Agreement.

k. *Assignment*. You will not assign or transfer this Agreement, including any
assignment or transfer by reason of merger, reorganization, sale of all or
substantially all of your assets, change of control or operation of law,
without our prior written consent, which will not be unreasonably withheld. We
may assign this Agreement to any affiliate or in the event of merger,
reorganization, sale of all or substantially all of our assets, change of
control or operation of law.

l. *No Third Party Beneficiaries*. Nothing in this Agreement, express or
implied, is intended to or shall confer upon any third party person or entity
any right, benefit or remedy of any nature whatsoever under or by reason of
this Agreement.

m. *Contract for Services*. This Agreement is a contract for the provision of
services and not a contract for the sale of goods. The provisions of the
Uniform Commercial Code (UCC), the Uniform Computer Information Transaction Act
(UCITA), or any substantially similar legislation as may be enacted, shall not
apply to this Agreement. If you are located outside of the territory of the
United States, the parties agree that the United Nations Convention on
Contracts for the International Sale of Goods shall not govern this Agreement
or the rights and obligations of the parties under this Agreement.

