---
layout: legal
title: "Privacy Policy"
date: November 3, 2015
author: Erik LaBianca <erik@7thsense.io>
---
= Privacy Policy

Telepath Data, Inc. dba Seventh Sense (“Seventh Sense”, “we” or “us”) knows that you care about how your personal information is used and shared - and we take your privacy seriously. This privacy policy ("Privacy Policy") applies to both our websites (Websites), including +++<u>+++www.theseventhsense.com+++</u>+++, and our Subscription Service, including our associated mobile applications (Mobile Apps). This Privacy Policy governs our treatment of personally identifiable information ("Personal Information") and enterprise information ("Enterprise Information") (such as: CRM data, website clickstreams, marketing campaign data, files, email/calendar information, and contacts) that you submit, or Seventh Sense otherwise gathers, when you access or use the Service. Together, Personal Information and Enterprise Information will be referred to as "Information".

By using the www.theseventhsense.com website ("Site") or any of our applications (together with the Site, the "Service") you acknowledge that you accept the practices and policies outlined in this Privacy Policy, and you consent that we will collect, use, and share your information as set forth below.

== Information We Collect
We collect information to provide better services to all our users. In fact, without collected information, our service would be almost worthless! We collect information in the following ways:

 * *Information you give us*. For example, you must provide us your name and email address as part of the registration process. Later, you’ll have to provide us with authorization for various services we gather data from.
 * *Information you provide to our payment processor on our behalf*. Our service never directly interacts with your payment information. Instead, we facilitate connecting you directly to our payment processor, Recurly, who takes care of keeping your subscription up to date and storing your card information in a secure manner. Should you have concerns about the storage of your payment infrormation, Recurly’s privacy policy can be found at +++<u>+++https://recurly.com/legal/privacy/+++</u>+++. Such information will be used only for the purposes of processing payments to Seventh Sense for the Services.
 * *Information we gather on your behalf*. For example, after you’ve created an account you will probably want to create a “connector” to Hubspot, Gmail or Exchange. You will have to provide us with credentials or, whenever possible, an authorization grant. We will gather information from the connector and use it to build your profiles. Seventh Sense does not access any information from these third-party services without your authorization. Except for Microsoft Exchange connectivity, the authentication process for 3rd party services is entirely managed by the third party. Seventh Sense never sees or stores your password to these services. In the case of Microsoft Exchange, Seventh Sense stores an encrypted version of your password which is never accessible in its original form, even to Seventh Sense personnel.
 * *Information we gather from your use of our service*. As a part of our commitment to deliver the best possible services, we gather a variety of information on an ongoing information. This information includes details such as what pages you might have visited, details about errors you may have experienced, how long various operations took, etc. We gather this information in a variety of ways, including:
 ** *Cookies*. Whenever you interact with our Service, we may automatically receive and record information on our server logs from your browser or device, which may include your IP address, device identification, "cookie" information, the type of browser and/or device you're using to access our Service, and the page or feature you requested. "Cookies" are identifiers we transfer to your browser or device that allow us to recognize your browser or device and tell us how and when pages and features in our Service are visited and by how many people. You may be able to change the preferences on your browser or device to prevent or limit your device's acceptance of cookies, but this may prevent you from taking advantage of some of our features. Also, if you click on a link to a third party website or service, such third party may also transmit cookies to you. Again, this Privacy Policy does not cover the use of cookies by any third parties, and we aren't responsible for their privacy policies and practices.
 ** *Logs*. We automatically generate and and store certain of information whenever you interact with the Service. Such information may include your account id, IP address, domain server, and type of Internet browser. This information helps us, among other things, analyze trends and administer the Service.

== Information We Do Not Collect
 * *Information about Children* The Website and Services are not intended for children under 13, and we do not knowingly collect information from children under the age of 13. Children aged 13 or older should not submit any personal information without the permission of their parents or guardians. By using the Website and Services, you are representing that you are at least 18, or that you are at least 13 years old and have your parents' or guardians’ permission to use Website and our related services. In the event that we learn that we have collected personal information from a child under age 13 we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us at +++<u>+++compliance@7thsense.io+++</u>+++
 * *Sensitive Information* refers to credit or debit card numbers, personal financial account information, Social Security numbers, passport numbers, driver's license numbers or similar personal identifiers, racial or ethnic origin, physical or mental health condition or information, or other employment, financial or health information. Seventh Sense does not collect or store sensitive information other than facilitating transfer to our payment provider.

== How We Use Your Information
 * *Information you give us* is used to allow you access to the Service, to allows us to communicate with you and to allow us to access other services on your behalf.
 * *Information you provide to our payment process on our behalf* is used solely for our mutual convenience in settling your account as per our Terms of Service.
 * *Information we gather on your behalf* is used to allow us to deliver the Service to you. Depending on the specific features and connectors involved, we will gather different amounts of information, but in all cases we gather that information solely on your behalf in order to deliver, repair, or improve the Services for you.
 * *Information we get from your usage of the service *is used to improve the Service by identifying problems, facilitating troubleshooting, and helping us to better understand our customers, their needs, and how the Services are being used and how they can be improved.

== Information We Share
 * *With Our Hosting Provider*. All your information will be stored at a third party hosting provider. We do this to provide the most cost effective, reliable, and secure Service that we can.
 * *With Our Agents*. We employ other companies and people to perform tasks on our behalf. Your information may be accessed by these partners/employees, in the event that we need to share your Information with them to provide our services or customer support to you. Unless we tell you differently, Seventh Sense's agents do not have any right to use Information we share with them beyond what is necessary to assist us.
 * *As Aggregate and **Anonymous** Information*. We may use, disclose or sell aggregate Information that has been anonymized by deleting personally identifiable data and references. This information does not identify you or the people you contact personally. We may share this data with our affiliates, agents and business partners. We may also disclose aggregate statistics in order to describe our services to current and prospective business partners, and to other third parties for other lawful purposes. [For example: We may track open rates across a variety of industries and compare batch vs. personalized delivery as part of an ROI study. We may also use this information to build cross-account profiles in order to make statement such as “users in California are most apt to read a marketing message at 11AM on a Monday.]
 * *Business Transfers*. In some cases, we may choose to buy or sell assets. In these types of transactions, customer information is typically one of the business assets that are transferred. Moreover, if Seventh Sense, or substantially all of its assets were acquired, or in the unlikely event that Seventh Sense goes out of business or enters bankruptcy, customer information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Seventh Sense may continue to use your Information as set forth in this policy.
 * *For Legal Compliance*. We may disclose your Information if required to do so by process of law, or if necessary in order to investigate fraud, a violation of our Terms of Use in connection with any harm being caused to a third party or their rights
 * *With Your Consent*. Except as set forth above, you will be notified when your Information may be shared with third parties, and will be able to prevent the sharing of this information.

== Retention of Your Information
If you would like to delete your account, please contact us directly via our support portal, located at https://theseventhsense.zendesk.com. You should be aware that it may not be technologically possible to remove each and every record of the information you have provided to us from our servers. The need to back-up our systems to protect information from inadvertent loss means that a copy of your Personal Information may exist in a non-erasable form that may be difficult or impossible for us to locate. In addition, we have the right to delete any account at any time if required to do so by process of law, or if necessary in order to investigate fraud, a violation of our Terms of Use or in connection with any harm being caused to a third party or their rights.

== Information Security
We take precautions to ensure the security of your Information. However, we cannot guarantee that hackers or unauthorized personnel will not gain access to your Information despite our efforts. You should note that in using the Website and Services, your information will travel through third party infrastructures which are not under our control.

We cannot protect, nor does this Privacy Policy apply to, any information that you transmit to other users of the Website. You should never transmit personal or identifying information to other users.

In addition to the security measures referenced above, your Service account is protected by a password for your privacy and security. You must prevent unauthorized access to your account and information by selecting and protecting your password appropriately and limiting access to your computer or device and browser by signing off after you have finished accessing your account.

== Changes to this Privacy Policy
This Privacy Policy was last changed on the date set forth at the top of the policy. We're constantly trying to improve the Service, so we may need to change this Privacy Policy from time to time as well, but we will alert you to material changes by posting the revised Privacy Policy on our Websites, and, if you subscribe to our Subscription Service, by sending you an email or providing a notification through your Service account, and/or by some other means. In addition, we will also edit the date at the top of this policy to reflect the date of the changes. Please note that if you've opted not to receive legal notice emails from us (or you haven't provided us with your email address), those legal notices will still govern your use of the Service, and you are still responsible for reading and understanding them. If you use the Service after any changes to the Privacy Policy have been posted, that means you agree to all of the changes. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is collected.

== Contacting Us
If you have any questions or concerns regarding our privacy practices, please send us a detailed message to support@theseventhsense.com +
or: +
Telepath Data, Inc.,  +
2017 N Dinwiddie Street,  +
Arlington,  +
VA 22207.

